import * as Berries from './berries'
import * as Contests from './contests'
import * as Encounters from './encounters'
import * as Evolution from './evolution'
import * as Games from './games'
import * as Items from './items'
import * as Locations from './locations'
import * as Machines from './machines'
import * as Moves from './moves'
import * as Pokemon from './pokemon'
import * as Utility from './utility'

export const Endpoints = {
  GetBerry: Berries.Endpoints.GetBerry,
  ListBerries: Berries.Endpoints.ListBerries,
  GetBerryFirmness: Berries.Endpoints.GetBerryFirmness,
  ListBerryFirmnesses: Berries.Endpoints.ListBerryFirmnesses,
  GetBerryFlavor: Berries.Endpoints.GetBerryFlavor,
  ListBerryFlavors: Berries.Endpoints.ListBerryFlavors,
  GetContestEffect: Contests.Endpoints.GetContestEffect,
  ListContestEffects: Contests.Endpoints.ListContestEffects,
  GetContestType: Contests.Endpoints.GetContestType,
  ListContentType: Contests.Endpoints.ListContentType,
  GetSuperContestEffect: Contests.Endpoints.GetSuperContestEffect,
  ListSuperContestEffects: Contests.Endpoints.ListSuperContestEffects,
  GetEncounterConditionValue: Encounters.Endpoints.GetEncounterConditionValue,
  ListEncounterConditionValues: Encounters.Endpoints.ListEncounterConditionValues,
  GetEncounterCondition: Encounters.Endpoints.GetEncounterCondition,
  ListEncounterConditions: Encounters.Endpoints.ListEncounterConditions,
  GetEncounterMethod: Encounters.Endpoints.GetEncounterMethod,
  ListEncounterMethods: Encounters.Endpoints.ListEncounterMethods,
  GetEvolutionChain: Evolution.Endpoints.GetEvolutionChain,
  ListEvolutionChains: Evolution.Endpoints.ListEvolutionChains,
  GetEvolutionTrigger: Evolution.Endpoints.GetEvolutionTrigger,
  ListEvolutionTriggers: Evolution.Endpoints.ListEvolutionTriggers,
  GetGeneration: Games.Endpoints.GetGeneration,
  ListGenerations: Games.Endpoints.ListGenerations,
  GetPokedex: Games.Endpoints.GetPokedex,
  ListPokedexes: Games.Endpoints.ListPokedexes,
  GetVersion: Games.Endpoints.GetVersion,
  ListVersions: Games.Endpoints.ListVersions,
  GetVersionGroup: Games.Endpoints.GetVersionGroup,
  ListVersionGroups: Games.Endpoints.ListVersionGroups,
  GetItem: Items.Endpoints.GetItem,
  ListItems: Items.Endpoints.ListItems,
  GetItemAttribute: Items.Endpoints.GetItemAttribute,
  ListItemAttributes: Items.Endpoints.ListItemAttributes,
  GetItemCategory: Items.Endpoints.GetItemCategory,
  ListItemCategories: Items.Endpoints.ListItemCategories,
  GetItemFlingEffect: Items.Endpoints.GetItemFlingEffect,
  ListItemFlingEffects: Items.Endpoints.ListItemFlingEffects,
  GetItemPocket: Items.Endpoints.GetItemPocket,
  ListItemPockets: Items.Endpoints.ListItemPockets,
  GetLocationArea: Locations.Endpoints.GetLocationArea,
  ListLocationAreas: Locations.Endpoints.ListLocationAreas,
  GetLocation: Locations.Endpoints.GetLocation,
  ListLocations: Locations.Endpoints.ListLocations,
  GetPalParkArea: Locations.Endpoints.GetPalParkArea,
  ListPalParkAreas: Locations.Endpoints.ListPalParkAreas,
  GetRegion: Locations.Endpoints.GetRegion,
  ListRegions: Locations.Endpoints.ListRegions,
  GetMachine: Machines.Endpoints.GetMachine,
  ListMachines: Machines.Endpoints.ListMachines,
  GetMoveAilment: Moves.Endpoints.GetMoveAilment,
  ListMoveAilments: Moves.Endpoints.ListMoveAilments,
  GetMoveBattleStyle: Moves.Endpoints.GetMoveBattleStyle,
  ListMoveBattleStyles: Moves.Endpoints.ListMoveBattleStyles,
  GetMoveCategory: Moves.Endpoints.GetMoveCategory,
  ListMoveCategories: Moves.Endpoints.ListMoveCategories,
  GetMoveDamageClass: Moves.Endpoints.GetMoveDamageClass,
  ListMoveDamageClasses: Moves.Endpoints.ListMoveDamageClasses,
  GetMoveLearnMethod: Moves.Endpoints.GetMoveLearnMethod,
  ListMoveLearnMethods: Moves.Endpoints.ListMoveLearnMethods,
  GetMoveTarget: Moves.Endpoints.GetMoveTarget,
  ListMoveTargets: Moves.Endpoints.ListMoveTargets,
  GetMove: Moves.Endpoints.GetMove,
  ListMoves: Moves.Endpoints.ListMoves,
  GetAbility: Pokemon.Endpoints.GetAbility,
  ListAbilities: Pokemon.Endpoints.ListAbilities,
  GetCharacteristic: Pokemon.Endpoints.GetCharacteristic,
  ListCharacteristics: Pokemon.Endpoints.ListCharacteristics,
  GetEggGroup: Pokemon.Endpoints.GetEggGroup,
  ListEggGroups: Pokemon.Endpoints.ListEggGroups,
  GetGender: Pokemon.Endpoints.GetGender,
  ListGenders: Pokemon.Endpoints.ListGenders,
  GetGrowthRate: Pokemon.Endpoints.GetGrowthRate,
  ListGrowthRates: Pokemon.Endpoints.ListGrowthRates,
  GetNature: Pokemon.Endpoints.GetNature,
  ListNatures: Pokemon.Endpoints.ListNatures,
  GetPokeathlonStat: Pokemon.Endpoints.GetPokeathlonStat,
  ListPokeathlonStats: Pokemon.Endpoints.ListPokeathlonStats,
  GetPokemon: Pokemon.Endpoints.GetPokemon,
  ListPokemon: Pokemon.Endpoints.ListPokemon,
  GetPokemonColor: Pokemon.Endpoints.GetPokemonColor,
  ListPokemonColors: Pokemon.Endpoints.ListPokemonColors,
  GetPokemonForm: Pokemon.Endpoints.GetPokemonForm,
  ListPokemonForms: Pokemon.Endpoints.ListPokemonForms,
  GetPokemonHabitat: Pokemon.Endpoints.GetPokemonHabitat,
  ListPokemonHabitats: Pokemon.Endpoints.ListPokemonHabitats,
  GetPokemonLocationAreas: Pokemon.Endpoints.GetPokemonLocationAreas,
  GetPokemonShape: Pokemon.Endpoints.GetPokemonShape,
  ListPokemonShapes: Pokemon.Endpoints.ListPokemonShapes,
  GetPokemonSpecies: Pokemon.Endpoints.GetPokemonSpecies,
  ListPokemonSpecies: Pokemon.Endpoints.ListPokemonSpecies,
  GetStat: Pokemon.Endpoints.GetStat,
  ListStats: Pokemon.Endpoints.ListStats,
  GetPokemonType: Pokemon.Endpoints.GetPokemonType,
  ListPokemonTypes: Pokemon.Endpoints.ListPokemonTypes,
  GetLanguage: Utility.Endpoints.GetLanguage,
  ListLanguages: Utility.Endpoints.ListLanguages
}
