declare module 'eslint-plugin-check-file'
declare module 'eslint-plugin-boundaries'
declare module 'eslint-plugin-import'
declare module 'eslint-plugin-react-hooks'
declare module 'eslint-plugin-react-refresh'
